### ISSUE TITLE
About anisotropic transport.

### ISSUE THREAD

**Issue by plasmon1977** [hackingmaterials/amset#140]
Dear Developers,

In the PRB 2015 paper, the anisotropic dependence is averaged. I just wonder whether the new version of amset can be used to calculate anisotropic mobilities?Thank you!

Hao Zhang

**Comment by utf** [comment]
Hi Hao,

The new version of AMSET is specifically designed to account for anisotropic, multi band systems.
AMSET is no longer based on parabolic band structures and therefore includes anisotropy from  the electron group velocities and the scattering rates.

In the text log, the mobility and Seebeck coefficient tensors are averaged but the full tensor can be found in the `amset_data.json` file.

Best,
Alex
