### ISSUE TITLE
Queries with AMSET inputs...

### ISSUE THREAD

**Issue by rajanpir** [hackingmaterials/amset#162]
Dear Sir/Madam, Thanks for the AMSET...
I have following queries. Can you please answer my doubts...
1) Regrading the deformation potential of VBM and CBM, can we take the average of deformation potential of +1 and -1 % strain (compressive and tensile).
2) Which way of taking high frequency dielectric constant is more reliable. One with the VASP DFPT or from the LO and TO phonon frequencies and estimate the value of the high-frequency dielectric constant using the Lyddane-Sachs-Teller
relation.
3) For the elastic constant, whether only spherically averaged longitudinal elastic constants is enough or do we take the average of both transverse and longitudinal spherically averaged elastic constants
4) Will skipping the piezoelectric constants will effects the transport properties with AMSET...

Thanks in Advance...

**Comment by utf** [comment]
Hi @rajanpir. Thanks for trying out AMSET.

1. ±1 strain is very large. You can try ±0.05 % instead. You should ensure that you align your eigenvalues to a reference energy, such as the average electrostatic energy at the atomic cores (see `LVTOT` or `LVHAR` in vasp).
2. I would suggest calculating the dielectric constant using DFPT. This should be fine except for very small band gap materials (< 0.2 eV), in which case you should use hybrid DFT and the `LCACLEPS` tag. If you use DFPT you can extract the "effective polar optical phonon frequency" needed in polar optical phonon scattering using the command `amset phonon-frequency vasprun.xml` where `vasprun.xml` is the output from the DFPT calculation.
3. For now you should just use the longitudinal spherically averaged elastic constants. But soon I will include the ability to support the full elastic constant tensor.
4. Piezoelectric scattering will only be important if your system belongs to one of the piezoelectric space groups and at low temperatures < 300 K.

Best,
Alex

**Comment by rajanpir** [comment]
Dear Sir,
   Thank you very much...  Your suggestions works well for my investigating materials. However, in case of any other crystal system other than cubic (like orthorhombic), how to calculate the longitudinal spherically averaged elastic constants. From aMoBT manual, I have taken the formula to compute the spherically averaged elastic constants for cubic system... In case of other crystal systems how to handle this parameter? Any suggestions from you...? Thanks...
