### ISSUE TITLE
Error for spin-resolved HSE06 calculation with SOC

### ISSUE THREAD

**Issue by SimonMel** [hackingmaterials/amset#166]
[Output AMSET.txt](https://github.com/hackingmaterials/amset/files/4898115/Output.AMSET.txt)
[HSE_DOS.txt](https://github.com/hackingmaterials/amset/files/4898119/HSE_DOS.txt)

Dear,

To become familiar with AMSET, I tried to re-do the example of Si that is provided with the code, with the only difference that I did the band structure calculation myself. In the attached file you can find my VASP input file that I used, I performed a hybrid functional calculation with spin-orbit coupling taken into account. However, I obtain an error which I tried to trace back in the code but I was not able to find the issue. You can find my output of the amset run in the attached file. For the settings file I simply used the same file as of the Si example with only minor changes for the input values. I hope you can help me out. Thank you in advance for your help.

Kind regards,
Simon

**Comment by utf** [comment]
Hi Simon,

AMSET can calculate wavefunction overlaps using either the orbital projections or wave-function coefficients. The preferred method is using the wavefunction coefficients but this approach does not yet support spin–orbit coupling. If you wish to use the orbital projection approach, you need to make sure that VASP includes the projection data in the vasprun.xml file. You can do this by adding the following tag to the INCAR file:

```
LORBIT = 11
```

Please let me know if that fixes the problem.

**Comment by SimonMel** [comment]
This solved the problem! Thank you for the quick response and the great code! 
Best regards,
Simon
