### ISSUE TITLE
Accuracy depending on "performance settings"

### ISSUE THREAD

**Issue by SimonMel** [hackingmaterials/amset#167]
I had an additional question for which I opened a new issue such that other new users can easily find the information needed.

I played a bit with the performance settings (energy_cutoff, fd_tol, dos_estep, symprec) and found quite some changes in the resulting mobility. Is it in general correct to minimize/maximize these values to increase the accuracy of the calculations or are there some inconsistencies for minimizing/maximizing these settings?
- energy_cutoff: maximize
- fd_tol: minimize
- dos_estep: minimize
- symprec: minimize

In addition is there some preference in minimizing/maximizing one of these settings?

**Comment by utf** [comment]
The preference for maximising/minimising each property is exactly as you suggest. In general, the default values should be sufficient to give converged results. If you want to be thorough, the order of importance (descending order is):

1. `fd_tol`: This determines the number of k-points for which the scattering rates are calculated explicitly. I've attached a figure that shows the convergence of Seebeck, mobility and electronic component of lattice thermal conductivity with `fd_tol` (lambda in the graph). The y axis shows the percentage difference versus an `fd_tol` of 0 (i.e., all k-points calculated explicitly). The default value of `fd_tol` is 0.05, at which all properties are converged to within ~1 % (shown by the dashed grey lines).
<img width="572" alt="Screenshot 2020-07-09 at 12 58 18" src="https://user-images.githubusercontent.com/1330638/87085771-4951f180-c1e5-11ea-88eb-3e0070a0eabf.png">

2. `dos_estep` : Changing this can alter i) the fermi level position ii) the integration of the transport properties. However, decreasing this value significantly can dramatically increase the run time with little effect on the transport properties. If you do some more rigorous testing on this, I would be happy to change the default, but from my testing it seems fine.

The last two parameters I expect to basically have no effect:

3. `energy_cutoff`: Controls the number of bands included in the calculation. The default is 1.5 eV, which means that any bands that contain at least one k-point with an energy within this value of the CBM/VBM (or Fermi level in metals) will be included. As transport is generally controlled by the states < ~500 meV of the band edge I think changing this will have no effect.
4. `symprec`: Unless your system is very close to being a different symmetry this shouldn't have any impact.

In general, the most important parameter is `interpolation_factor` which controls the density of the interpolation. It is important to converge your results with respect to this. Here, larger values indicate greater interpolation density.

**Comment by utf** [comment]
I should also mention, that you can trial multiple fd_tol values at once by supplying a list of values: I.e., `fd_tols = [0.1, 0.01, 0.001]` etc. The scattering rates are first calculated according to the lowest fd_tol value, and then the transport is solved using the different values.

**Comment by SimonMel** [comment]
Ok thank you very much for your help! I appreciate!
