### ISSUE TITLE
KeyError: <Spin.up: 1> when calculating SnS

### ISSUE THREAD

**Issue by lycheelee54** [hackingmaterials/amset#184]
Dear developer,

I recently met an error when trying to calculate the relaxation time of SnS compound. I have attached my amset.log and my setting.yaml. It seems that error happens when the code is trying to calculate the band overlap. But I didn't use any tags related to SOC or spin polarization in my INCAR. Hope you can tell me where it goes wrong. Thank you very much!

Best,
Zhi

[settings.yaml.txt](https://github.com/hackingmaterials/amset/files/5013761/settings.yaml.txt)
[amset.log](https://github.com/hackingmaterials/amset/files/5013787/amset.log)

**Comment by utf** [comment]
Hi @lycheelee54, AMSET can calculate wavefunction overlaps using either the orbital projections or wave-function coefficients. The preferred method is using the wavefunction coefficients. If you wish to use the orbital projection approach, you need to make sure that VASP includes the projection data in the vasprun.xml file. You can do this by adding the following tag to the INCAR file:

```
LORBIT = 11
```

I will release a tutorial on using the wavefunction coefficients soon.

**Comment by lycheelee54** [comment]
Hello @utf , I have use the command:
`amset dump-wavefunction`
to extract the wave-funtion coefficients from WAVECAR, and generate the coeffs.h5 file in the current directory. But after I ran amset, again I meet the same Keyerror:<Spin:1> problem. Is there any other thing I missed when preparing the wave-function coefficient?11
On the other hand, this error fixed by applying the orbital projection approach you mentioned. Thanks for your timely response!

Best,
Zhi

**Comment by utf** [comment]
Hi Zhi. Good to see you found `dump_wavefunction`! You then need to specify the path to the coefficients file using the [`wavefunction_coefficients` AMSET option](https://hackingmaterials.lbl.gov/amset/settings/#wavefunction_coefficients). For example, if your coefficients file is in the current directory, you would set in the settings yaml:

```yaml
wavefunction_coefficients: coeffs.h5
```

Just FYI, in the next version, the `dump_wavefunction` command will be renamed to just `wavefunction`, the new version will not need pawpawseed, and the coefficients file will be much smaller.

**Comment by lycheelee54** [comment]
Hi @utf ,

Thanks for your detailed instruction. Looking forward to the update of AMSET.

Best,
Zhi
