### ISSUE TITLE
Request to clarify AMSET inputs

### ISSUE THREAD

**Issue by rajanpir** [hackingmaterials/amset#190]
Dear Sir, 
 1)Using the command amset phonon-frequency, two frequencies were obtained max. freq and eff. freq. Shall we use the use max. frequency instead of eff.frequency for AMSET calculations which matches with examples cases like GaAs and Si.
2) I understand that we can take the average of longitudinal elastic constants (C11 + C22 + C33) to determine the elastic constants. Please let us know whether full elastic tensor have been implemented in current version.
3) Is it fine to calculate properties with AMSET without wave-functions dump option. I have included LORBIT=11 in my calculation and use only the vasprun.xml.

**Comment by lycheelee54** [comment]
Dear rajanpir and Alex,

I am also tangling with the "pop_frequency" tag in the setting.yaml these days. In AMSET example, it happens that both GaAs and Si system only have one LO-TO splitting phonon band, so it seems that LO happens to be the phonon band with the highest phonon frequency. But in SnS system I calculate, there seems to be more than one optic phonon band that are splitting. So should I still use "the frequency of the highest phonon band" as the input in "pop_frequency" tag?

Also I have read the part about using command
`amset phonon-frequency`
to extract the weighted-sum polar optic phonon frequency. Is this method helps in solving the problems I met in SnS? Anyway ,I ran the command but only get a effective frequency equals 0 THz. I don't know if this means my DFPT calculation goes wrong?

FYI, I have attached the phonon dispersion of SnS I calculated here and the output after I entered the command `amset phonon-frequency` in SnS DFPT calculation directory:

![image](https://user-images.githubusercontent.com/62397758/89588013-65f34080-d808-11ea-8095-25e027a66cab.png)

  Frequency    Weight
-----------  --------
      -0.01      0.00
      -0.01      0.00
      -0.00      0.00
      -0.00      0.00
      -0.00      0.00
      -0.00      0.00
       0.00      0.06
       0.00      0.94
       0.00      0.00
       0.00      0.00
       1.11      0.00
       1.92      0.00
       2.00      0.00
       2.34      0.00
       2.76      0.00
       2.86      0.00
       5.12      0.00
       5.43      0.00
       5.56      0.00
       6.20      0.00
       6.47      0.00
       6.61      0.00
       6.63      0.00
       8.25      0.00

effective frequency: 0.00 THz

Best,
Zhi

**Comment by utf** [comment]
Hi @rajanpir and @lycheelee54,

Thanks for your questions and your interest in AMSET. I am hoping to keep the GitHub only for bug reports from now on. If you have questions on how to use the code, please instead post them to the help forum: https://matsci.org/c/amset/17

I have moved both of your questions to the forum and answered them there:
@rajanpir: https://matsci.org/t/request-to-clarify-amset-inputs/4731
@lycheelee54: https://matsci.org/t/question-on-polar-optical-phonon-frequency/4733

Please continue the discussion on the forum.

Best,
Alex

**Comment by lycheelee54** [comment]
Hi Alex,

It seems that MATSCI forum doesn't support any file uploading except pictures, I'm sorry that I have to upload my files here temporarily. Once I figure out how to upload there I will keep discuss with you on MATSCI forum.
[INCAR.txt](https://github.com/hackingmaterials/amset/files/5042424/INCAR.txt)
[OUTCAR.txt](https://github.com/hackingmaterials/amset/files/5042431/OUTCAR.txt)
[KPOINTS.txt](https://github.com/hackingmaterials/amset/files/5042435/KPOINTS.txt)
[OSZICAR.txt](https://github.com/hackingmaterials/amset/files/5042436/OSZICAR.txt)
[POSCAR.txt](https://github.com/hackingmaterials/amset/files/5042439/POSCAR.txt)

Best,
Zhi

**Comment by lycheelee54** [comment]
Hi Alex,

It seems that MATSCI doesn't support any file uploading except pictures. I am sorry that I have to upload my input file for DFPT run here. We can still discuss at MATSCI forum.
[INCAR.txt](https://github.com/hackingmaterials/amset/files/5042747/INCAR.txt)
[OUTCAR.txt](https://github.com/hackingmaterials/amset/files/5042748/OUTCAR.txt)
[POSCAR.txt](https://github.com/hackingmaterials/amset/files/5042749/POSCAR.txt)
[KPOINTS.txt](https://github.com/hackingmaterials/amset/files/5042750/KPOINTS.txt)
[OSZICAR.txt](https://github.com/hackingmaterials/amset/files/5042751/OSZICAR.txt)

Thanks,
Zhi

**Comment by utf** [comment]
Hi Zhi, can you also send over the input/output files of your relaxation?

**Comment by utf** [comment]
Also, I notice you are using a Monkhurst Pack grid rather than Gamma centred. 

For AMSET itself, you need to use a Gamma centred grid (it doesn't work well with Monkhurst Pack). I would also recommend trying your relaxation and DFPT calculations with Gamma centred too.

**Comment by lycheelee54** [comment]
Hi Alex,

Here are my input/output files of relaxation (the OUTCAR is over 10 MB and cannot be upload, so I have to substitute it with a log file). It never occurs to me that the problem should lie in k-mesh. Thanks for the suggestion. I'll try rerun the relaxation and DFPT with Gamma centerd k mesh.



Thank you,
Zhi
[KPOINTS.txt](https://github.com/hackingmaterials/amset/files/5043021/KPOINTS.txt)
[POSCAR.txt](https://github.com/hackingmaterials/amset/files/5043022/POSCAR.txt)
[CONTCAR.txt](https://github.com/hackingmaterials/amset/files/5043024/CONTCAR.txt)
[output.txt](https://github.com/hackingmaterials/amset/files/5043039/output.txt)
[INCAR.txt](https://github.com/hackingmaterials/amset/files/5043052/INCAR.txt)

**Comment by utf** [comment]
Hi @lycheelee54. The CONTCAR from your relaxation does not match the POSCAR you used in the DFPT calculation. Can you check you are using the full converged structure for your DFPT run.

**Comment by lycheelee54** [comment]
Hello Alex,

Sorry I uplaoded the wrong POSCAR for DFPT calculation. Anyway, I have rerun both the relaxation and DFPT calcualtion, with tight convergence criterion and Gamma centered KPOINTS. But I still get the abnormal 0 THz effective frequency. I find out that POSCAR hasn't changed much and all the other outputs are to some extent similar with the old ones. It seems that problem doesn't lie in POSCAR or KPOINTS? I still attached all the input/output files for your information. Thanks you so much for the patient response and kindly help.
[INCAR_relax.txt](https://github.com/hackingmaterials/amset/files/5046559/INCAR_relax.txt)
[KPOINTS_relax.txt](https://github.com/hackingmaterials/amset/files/5046560/KPOINTS_relax.txt)
[POSCAR_relax.txt](https://github.com/hackingmaterials/amset/files/5046561/POSCAR_relax.txt)
[CONTCAR_relax.txt](https://github.com/hackingmaterials/amset/files/5046562/CONTCAR_relax.txt)
[OUTCAR_relax.txt](https://github.com/hackingmaterials/amset/files/5046563/OUTCAR_relax.txt)
[INCAR_DFPT.txt](https://github.com/hackingmaterials/amset/files/5046564/INCAR_DFPT.txt)
[KPOINTS_DFPT.txt](https://github.com/hackingmaterials/amset/files/5046565/KPOINTS_DFPT.txt)
[POSCAR_DFPT.txt](https://github.com/hackingmaterials/amset/files/5046566/POSCAR_DFPT.txt)
[OSZICAR_DFPT.txt](https://github.com/hackingmaterials/amset/files/5046567/OSZICAR_DFPT.txt)
[OUTCAR_DFPT.txt](https://github.com/hackingmaterials/amset/files/5046568/OUTCAR_DFPT.txt)

Thanks,
Zhi

**Comment by utf** [comment]
Hi @lycheelee54, I cannot see anything wrong in your input files, however your DFPT calculation output is bad (contains 10 zero frequency gamma point phonon modes).

The only thing I can think of is that your VASP version is very old (v5.3.1) I know there have been many bug fixes since then, so perhaps they fixed something to do with DFPT. I would suggest seeing if a more recent VASP version fixes your problem.

Best,
Alex

**Comment by lycheelee54** [comment]
Hi Alex,

It works! After I changed to VASP 5.4.4 and reran the DFPT calculation, The output of effective frequency is now like this:
 Frequency    Weight
      -0.01      0.00
      -0.01      0.00
      -0.00      0.00
       1.11      0.00
       1.44      0.00
       1.62      0.00
       1.92      0.03
       1.99      0.00
       2.01      0.00
       2.34      0.00
       2.76      0.00
       2.88      0.11
       4.10      0.33
       4.74      0.00
       5.13      0.21
       5.42      0.23
       5.57      0.00
       5.62      0.00
       6.06      0.00
       6.21      0.04
       6.49      0.00
       6.62      0.00
       6.64      0.05
       8.25      0.00
effective frequency: 4.62 THz

It now correctly shows 3 zero frequency phonon modes corresponding to 3 acoustic phonon modes. Thank you so much!

Best,
Zhi
