### ISSUE TITLE
Atomate AMSET workflow?

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/amset#356]
Any plans to add a fireworks workflow for running AMSET through `atomate`?

**Comment by ardunn** [comment]
I believe there was a workflow in progress at some point, but seeing as the main dev @utf has moved onto a new fellowship, I'm not sure it's his main focus anymore

**Comment by utf** [comment]
I've developed an AMSET workflow using [atomate2](https://github.com/materialsproject/atomate2). The workflow automatically calculates all materials properties, deformation potentials, the HSE band gap, and dense electronic structure, and then iteratively runs AMSET with increasing interpolation factor until the transport properties are converged.

The workflow is still being tested but I encourage you to check out atomate2 for the other workflows for the time being.
