### ISSUE TITLE
Docs Clarification on OMP_NUM_THREADS/nworkers?

### ISSUE THREAD

**Issue by ikirker** [hackingmaterials/amset#358]
As a suggestion, from someone who was briefly confused: the documentation at <https://github.com/hackingmaterials/amset/blob/main/docs/src/using.md> has a call-out box containing this:

> ***Obtaining best performance***
>
> To obtain the best performance, it is recommended to run `export OMP_NUM_THREADS=1` before running AMSET.

It wasn't clear to me whether this meant I would simply be running AMSET in serial by doing so until I searched the Discourse and found the `nworkers` setting. I think it might be worth clarifying that there, possibly with something like:

> ***Obtaining best performance***
>
> To obtain the best performance, it is recommended to run `export OMP_NUM_THREADS=1` before running AMSET. 
> Use the `nworkers` setting in the [settings file](settings.md#nworkers) if you want to run AMSET using multiple cores.

**Comment by utf** [comment]
Hi @ikirker,

Thank you for the suggestion. I've updated the docs accordingly.

Please let me know if anything else in the documentation is unclear/doesn't contain enough information.

Best,
Alex
