### ISSUE TITLE
Make Amset run from a BandStructure

### ISSUE THREAD

**Issue by utf** [hackingmaterials/amset#39]
Currently, Amset requires a pymatgen `Vasprun` object as an input parameter. As we only need the structural and eigenvalue properties from this object, we should transition to requiring a pymatgen `BandStructure` object instead.

This will make Amset compatible with codes other than VASP.

**Comment by albalu** [comment]
I just remembered that I do read s- and p-orbital contributions to the bands also from vasprun.xml; this can also be read from a CompleteDos object.
