### ISSUE TITLE
How to calculate the low(high)-frequency dielectric constant correctly?

### ISSUE THREAD

**Issue by ywu2019** [hackingmaterials/amset#49]
When we try to repeat the example of PbTe, the calculated low-frequency dielectric constant (epsilon_s) using vasp is 26 rather than the 44 value in the example. Besides, we want to know how to get the epsilon_inf and W_POP value. Thank you.

**Comment by utf** [comment]
The calculation of the static dielectric constant depends on many factors, including DFT functional, energy cut-off, k-point mesh, initial force conversion criteria, energy conversion criteria, FFT mesh density, etc.

For the polar optical phonon frequency we take the highest energy optical phonon frequency at the Gamma point, taken either from a DFPT calculation or from phonopy.

You can calculate the high-frequency dielectric constant using the [LOPTICS](https://cms.mpi.univie.ac.at/wiki/index.php/LOPTICS) tag in VASP. Note for accurate values, often a hybrid functional is needed and the calculation needs many empty bands (generally, you should converge the high-frequency dielectric with respect to number of bands).
