### ISSUE TITLE
License

### ISSUE THREAD

**Issue by afonari** [hackingmaterials/amset#53]
Great code, congrats!

This is a license question. amset is licensed under BSD (?) as per: https://github.com/hackingmaterials/amset/blob/master/LICENSE

However it uses GPLv3 licensed BoltzTrap (https://gitlab.com/sousaw/BoltzTraP2/blob/public/LICENSE.txt), for example in amset/amset/transport.py:
```
from BoltzTraP2.bandlib import fermiintegrals, calc_Onsager_coefficients, DOS, \
lambda_to_tau, BTPDOS
```

This makes the amset code also GPLv3. Can you please clarify and/or (hopefully) correct me if I'm wrong.

**Comment by utf** [comment]
Hi @afonari, thank you for your interest in AMSET.

We are releasing AMSET under a modified BSD license as you suggested.

Although, BoltzTraP2 is used by the package, we are not distributing any of the BoltzTraP2 source code along with AMSET.

Additionally, if other interpolation methods become available, we will add support for these, meaning BoltzTraP2 will not be required for AMSET to run.
