### ISSUE TITLE
M1 compatible?

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/amset#571]
Getting an odd error from `pip install amset` on M1 MacBook Pro. Anyone seen this before?

```py
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

<details>
<summary>logs</summary>

```py
mpy_e28db8833d8c4d28b325d122e2851bbe/numpy/_build_utils/src/apple_sgemv_fix.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-12-arm64-3.10/numpy/core/src/umath -Ibuild/src.macosx-12-arm64-3.10/numpy/core/src/npymath -Ibuild/src.macosx-12-arm64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-12-arm64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/janosh/.venv/py310/include -I/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/include/python3.10 -Ibuild/src.macosx-12-arm64-3.10/numpy/core/src/common -Ibuild/src.macosx-12-arm64-3.10/numpy/core/src/npymath -c numpy/core/src/multiarray/alloc.c -o build/temp.macosx-12-arm64-3.10/numpy/core/src/multiarray/alloc.o -MMD -MF build/temp.macosx-12-arm64-3.10/numpy/core/src/multiarray/alloc.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

**Comment by utf** [comment]
I ran into this issue myself and got around it by installing numpy, h5py, numba, pyfftw, cmake through conda. To install boltztrap2 I had to run:

```
brew install gcc-11
CC=gcc-11 CXX=g++-11 pip install boltztrap2
```

And then finally amset was installed using `pip install amset`.

**Comment by zohansyahfatomi** [comment]
<img width="1680" alt="Screenshot 2024-01-26 at 23 15 42" src="https://github.com/hackingmaterials/amset/assets/6700004/c294179e-7d86-4839-aa7c-24a18591c83f">

I plan to install bolztrap2 on m1 mac. but i got error. I have followed your tutorial. anyone know why?

**Comment by koushikpalnu** [comment]
I have installed AMSET on M2 and sucessfully installed it but when running the examples, I am getting the FileNotFound Error [Errno 2]. Keeping the POTCAR file is not solving the problem. Any suggestion on how to resolve this?  `/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)

  Loading settings from: settings.yaml

  
    ERROR: amset exiting on 02 Feb 2024 at 17:03
  Traceback (most recent call last):
    File "/Users/koushik/anaconda3/envs/my_amset/bin/amset", line 8, 
  in <module>
      sys.exit(cli())
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/amset/tools/run.py", line 132, in run
      runner = Runner.from_directory(
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/amset/core/run.py", line 388, in from_directory
      return Runner.from_vasprun(input_file, settings)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/amset/core/run.py", line 341, in from_vasprun
      vasprun = Vasprun(vasprun, parse_projected_eigen=True)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/pymatgen/io/vasp/outputs.py", line 296, in __init__
      self.update_potcar_spec(parse_potcar_file)
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/pymatgen/io/vasp/outputs.py", line 1054, in 
  update_potcar_spec
      if potcar := self.get_potcars(path):
    File "/Users/koushik/anaconda3/envs/my_amset/lib/python3.10/site-
  packages/pymatgen/io/vasp/outputs.py", line 1010, in get_potcars
      f"{search_path}/{fn}" for fn in os.listdir(search_path) if 
  fn.startswith("POTCAR") and ".spec" not in fn
  FileNotFoundError: [Errno 2] No such file or directory: ''`
