### ISSUE TITLE
Conda dependency issue

### ISSUE THREAD

**Issue by sinazadeh** [hackingmaterials/amset#588]
Installing AMSET through Conda downgrades lots of packages, is there any plan to update the AMSET hosted in conda?
![image](https://user-images.githubusercontent.com/63080674/162275294-60f7e103-ff2f-4ae5-b6c7-402799145fde.png)

**Comment by utf** [comment]
I've release a new version, 0.4.16 which has less strict package requirements. Hopefully that works for you now.

**Comment by utf** [comment]
Ok, the conda version has also been updated!
